version: 1.0
name: NationMC
main: com.nationmc.me.Main
author: Wiz_Techno
description: Core commands for NationMC
depend: [TitleAPI, WorldGuard, WorldEdit]
commands:
  setrank:
    description: Rank Setter
    permission: nationmc.op
  gm:
    description: Gamemode Command
    permission: group.builder
    permission-message: Builder+ Command
  announce:
    description: Anounce Command
    permission: group.admin
    permission-message: Admin+ Command
  sa:
    description: Send message to staff
  sar:
    description: Reply to people who talked in Staff Chat
    permission: group.tmod
    permission-message: Trial Moderator+ Command
  won:
    description: For win effect in PvP Lobby
    permission: op
    permission-message: Admin+ Debug Command
  updater:
    description: Update server
    permission: group.admin
    permission-message: Admin+ Command
  pvp:
    description: Queue PvP
  e:
    description: Event Module
    permission: group.admin
    permission-message: Admin+ Command.
  raw:
    description: Test Chat Colors
    permission: group.admin
    permission-message: Admin+ Command
  server:
    description: Server teleport command
  lock:
    description: Server lockdown command
    permission: group.admin
    permission-message: Admin+ Command
  scorebaord:
    description: Scoreboard Message command
    permission: group.admin
    permission-message: Admin+ Command
  motd:
    description: Set MOTD
    permission: group.admin
    permission-message: Admin+ Command
  discord:
    description: Get discord link

permissions:
  nationmc.op:
    description: Gives access to all NationMC commands
    default: op
  nation.*:
    description: Nation MC Node
    default: notop
    children:
      nation.owner:
        default: notop
      nation.leader:
        default: notop
      nation.dev:
        default: notop
      nation.admin:
        default: notop
      nation.mod:
        default: notop
      nation.tmod:
        default: notop
      nation.builder:
        default: notop
      nation.default:
        default: notop
      