version: 1.0
name: NationMC
main: com.nationmc.me.Main
author: Wiz_Techno
description: Core commands for NationMC
depend: [TitleAPI, WorldGuard, WorldEdit]
commands:
  setrank:
    description: Rank Setter
    permission: nationmc.op
  gm:
    description: Gamemode Command
    permission: group.builder
  announce:
    description: Anounce Command
    permission: nationmc.op
  scoreboard:
    description: Scoreboard Setter
    permission: nationmc.op
  sa:
    description: Send message to staff
  sar:
    description: Reply to people who talked in Staff Chat
    permission: group.tmod
  won:
    description: For win effect in PvP Lobby
    permission: op
  updater:
    description: Update server
    permission: group.admin
  pvp:
    description: Queue PvP
  debug:
    description: debugggg
    permission: op
  e:
    description: Event Module
    permission: group.admin
  raw:
    description: Test Chat Colors
    permission: group.admin
  server:
    description: Server teleport command
  lockdown:
    description: Server lockdown command
    permission: group.admin
    

permissions:
  nationmc.op:
    description: Gives access to all NationMC commands
    default: op
  nation.*:
    description: Nation MC Node
    default: not op
    children:
      nation.owner:
        default: not op
      nation.leader:
        default: not op
      nation.dev:
        default: not op
      nation.admin:
        default: not op
      nation.mod:
        default: not op
      nation.tmod:
        default: not op
      nation.builder:
        default: not op
      nation.default:
        default: not op
      