version: 1.0
name: NationMC
main: com.nationmc.me.Main
author: Wiz_Techno
description: Core commands for NationMC
depend: [TitleAPI, WorldGuard, WorldEdit, LuckPerms]
commands:
  setrank:
    description: Rank Setter
    permission: nationmc.op
  gm:
    description: Gamemode Command
    permission: group.builder
    permission-message: Builder+ Command
  announce:
    description: Anounce Command
    permission: group.admin
    permission-message: Admin+ Command
  sa:
    description: Send message to staff
  sar:
    description: Reply to people who talked in Staff Chat
    permission: group.tmod
    permission-message: Trial Moderator+ Command
  updater:
    description: Update server
    permission: group.admin
    permission-message: Admin+ Command
  raw:
    description: Test Chat Colors
    permission: group.admin
    permission-message: Admin+ Command
  server:
    description: Server teleport command
  lock:
    description: Server lockdown command
    permission: group.admin
    permission-message: Admin+ Command
  scoreboard:
    description: Scoreboard Message command
    permission: group.admin
    permission-message: Admin+ Command
  motd:
    description: Set MOTD
    permission: group.admin
    permission-message: Admin+ Command
  discord:
    description: Get discord link
  news:
    description: News Command
    permission: group.admin
    permission-message: Admin+ Command
  worldtp:
    description: Teleport to different worlds.
    aliases: wtp
    permission: group.admin
    permission-message: Admin+ Command
  miniannounce:
    description: Send a mini-announcement.
    aliases: ma
    permission: group.admin
    permission-message: Admin+ Command

permissions:
  nationmc.op:
    description: Gives access to all NationMC commands
    default: op
  nation.*:
    description: Nation MC Node
    default: notop
    children:
      nation.owner:
        default: notop
      nation.leader:
        default: notop
      nation.dev:
        default: notop
      nation.admin:
        default: notop
      nation.mod:
        default: notop
      nation.tmod:
        default: notop
      nation.builder:
        default: notop
      nation.default:
        default: notop